### ISSUE TITLE
Unhandled Runtime Error Error: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ehamawy** [gregives/recommend.domains#50]
Running and opening the webui gives this error
Windows 10 22H2, latest npm and yarn

![thispage](https://github.com/gregives/recommend.domains/assets/9953712/985a9700-089d-497d-95cf-f42c6aac1665)

[log.txt](https://github.com/gregives/recommend.domains/files/13313076/log.txt)

**Comment by gregives** [comment]
Hi @ehamawy, that's because I'm using a private GitHub Gist for logging. I'll make a PR that removes the logging in development so that you can run it without error. In the meantime, you could just comment out the inside of the logging functions in `app/api/log.ts` which reference `process.env.GITHUB_TOKEN`

Hope that helps!

**Comment by Melodyxyy** [comment]
Hello, I have same problem as ehamawy, how to comment out the inside of the logging functions in app/api/log.ts which reference process.env.GITHUB_TOKEN? I revised as below but it couldn't perform correctly.

import { stringify } from "csv-stringify/sync";

const GIST_ID = "c3b6755871063529ad9d3067a2751462";

type Log = {
  description: string;
  suggestion: string;
  options: string;
  timestamp: number;
};

const logs: Log[] = [];

function queue(logsToQueue: Omit<Log, "timestamp">[]) {
  logs.push(
    ...logsToQueue.map((log) => ({
      ...log,
      timestamp: Date.now(),
    }))
  );
}

async function flush() {
  const logsToSend = logs.splice(0, logs.length);

  if (logsToSend.length === 0) {
    return;
  }

  // Commenting out the code that references process.env.GITHUB_TOKEN
  /*
  const gist = await fetch(`https://api.github.com/gists/${GIST_ID}`, {
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
    },
  }).then((response) => response.json());

  const filename =
    new Date(logsToSend[0].timestamp).toISOString().slice(0, 10) + ".csv";
  const file = gist.files[filename];

  const content =
    (file === undefined
      ? "Description,Suggestion,Timestamp,Options\n"
      : file.content) +
    stringify(
      logsToSend.map(({ description, suggestion, timestamp, options }) => [
        description,
        suggestion,
        timestamp,
        options,
      ])
    );

  await fetch(`https://api.github.com/gists/${GIST_ID}`, {
    method: "PATCH",
    cache: "no-store",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
    },
    body: JSON.stringify({
      files: {
        [filename]: {
          content,
        },
      },
    }),
  });
  */
}

async function count() {
  // Commenting out the code that references process.env.GITHUB_TOKEN
  /*
  const gist = await fetch(`https://api.github.com/gists/${GIST_ID}`, {
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
    },
    next: {
      revalidate: 3600,
    },
  }).then((response) => response.json());

  let numberOfDomainsGenerated = 10000;
  for (const file of Object.values(gist.files)) {
    // @ts-ignore
    numberOfDomainsGenerated += file.content.split("\n").length - 1;
  }

  return numberOfDomainsGenerated;
  */
}

export const log = {
  count,
  flush,
  queue,
};

**Comment by gregives** [comment]
I'm about to make a change which will remove the need for the GitHub environment variable when running recommend.domains locally, so it's easier to get started. Sorry that it took me so long to get around to it!
